name: Deploy

on: 
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  build:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.5'
      - run: npm ci
      - run: npm test
      - run: npm run build

  changelog:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_TOKEN }}
    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.REPO_TOKEN }}
        git-message: 'chore(release): {version}'
        output-file: 'CHANGELOG.md'

  update_release_draft:
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - name: Create Release Draft
        id: create_draft_release
        uses: release-drafter/release-drafter@v5
        with:
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      # - uses: eregon/publish-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      #   with:
      #     release_id: ${{ steps.create_draft_release }}

  publish:
    name: Publish to Github Packages
    runs-on: ubuntu-latest
    needs: changelog
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.5'
      - run: echo //npm.pkg.github.com/:_authToken=${{secrets.NPM_TOKEN}} >> ~/.npmrc
      - run: npm ci
      - run: npm publish