# This is a basic workflow that is manually triggered
name: Create Release PR

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Bump Version
        default: minor
        required: true
        options:
        - patch
        - minor
        - major

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  updateVersion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get node version
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.5'
      - name: Run CI
        run: npm ci
      - name: Update Version
        run: |
          git config user.name ${{ github.actor }}
          git config user.email '<>'
          npm run bump -- --release-as ${{ github.event.inputs.version }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: bump version
          title: 'chore(release): bump version'
          body: Bump version
          branch: testRelease
          base: main
          labels: stagex
