name: Pull request build

on: 
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:

  pr-lint:
    name: Verify title format
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.6.0
        with:
          title-regex: '^(BREAKING CHANGE|build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z ]+\))?: [\w ]+$'
          on-failed-regex-fail-action: true
          on-failed-regex-comment: >
            ## Pull request title linting :rotating_light:

            In order to merge this pull request, the title of the pull request should be prefixed by one of the available types.

            ### Available types:

              - **BREAKING CHANGE**: A major update
              - **feat**: A new feature
              - **fix**: A bug fix
              - **docs**: Documentation only changes
              - **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
              - **refactor**: A code change that neither fixes a bug nor adds a feature
              - **perf**: A code change that improves performance
              - **test**: Adding missing tests or correcting existing tests
              - **build**: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
              - **chore**: Other changes that don't modify src or test files
              - **revert**: Reverts a previous commit
            ---
            <details>
            <summary>Examples</summary>

                ```
                feat(grpc): add new endpoint
                refactor: combine class A and class B
                ci: update pull request linter
                style: change format of strings
                ```

            </details>

              :tipping_hand_person: For more examples, visit https://www.conventionalcommits.org/en/v1.0.0/#examples.
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.5'
      - run: npm ci
      - run: npm test
      - run: npm run build
  