name: Build status
on: 
  pull_request
jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.5'
      - run: npm install
      - run: npm test
      - run: npm run build
  