name: Build status
on: 
  pull_request
jobs:

  pr-lint:
    name: Pull request Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm install @commitlint/config-conventional
    - uses: JulienKode/pull-request-name-linter-action@v0.5.0

  build:
    name: Build App
    needs: pr-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.5'
      - run: npm ci
      - run: npm test
      - run: npm run build
  