name: Build status
on: 
  pull_request

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

jobs:
  pr-lint:
    name: Pull request Linting
    runs-on: ubuntu-latest
    steps:
      - name: Lint pull request title
        uses: jef/conventional-commits-pr-action@v1
        with:
          token: ${{secrets.REPO_TOKEN}}

  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.5'
      - run: npm ci
      - run: npm test
      - run: npm run build
  