# This is a basic workflow that is manually triggered

name: Release workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  release-workflow:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    # Runs a single command using the runners shell
    - name: Detect and Tag New Version
      id: tag-action
      uses: salsify/action-detect-and-tag-new-version@v2.0.1
    - name: Print the new version
      run: |
        echo "Current V ${{ steps.tag-action.current-version }}"
        echo "Previous V ${{ steps.tag-action.previous-version }}"
        echo "Tag ${{ steps.tag-action.tag }}"
    - name: Create Release Draft
      uses: release-drafter/release-drafter@v5
      with:
        publish: false
        version: ${{ steps.tag-action.current-version }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
