name: Hello World
on: push
jobs:
  build:
    name: Hello World action
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world!!"
    name: Hello World action again
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world again!!"